"""
Recommendations API
===================

Endpoints for retrieving access recommendations generated by confidence scoring.
"""

import os

import pandas as pd
from flask import Blueprint, jsonify, request

from models.session import get_session_path
from services.auth import require_auth

recommendations_bp = Blueprint("recommendations", __name__)


@recommendations_bp.route(
    "/api/sessions/<session_id>/recommendations", methods=["GET"]
)
@require_auth
def get_recommendations(session_id):
    """
    GET /api/sessions/<id>/recommendations
    Optional query params:
        ?level=HIGH        — filter by confidence level
        ?limit=100         — max rows returned (default: all)
    """
    try:
        session_path = get_session_path(session_id)
    except FileNotFoundError:
        return jsonify({"error": "Session not found"}), 404

    csv_path = os.path.join(session_path, "results", "recommendations.csv")
    if not os.path.isfile(csv_path):
        return jsonify({"error": "No recommendations. Run /mine first."}), 404

    df = pd.read_csv(csv_path, dtype=str)

    # Optional level filter
    level = request.args.get("level", "").upper()
    if level in ("HIGH", "MEDIUM"):
        df = df[df["confidence_level"] == level]

    # Optional limit
    limit = request.args.get("limit", type=int)
    if limit and limit > 0:
        df = df.head(limit)

    records = df.to_dict(orient="records")
    return jsonify({
        "session_id": session_id,
        "count": len(records),
        "recommendations": records,
    })


@recommendations_bp.route(
    "/api/sessions/<session_id>/recommendations/<user_id>", methods=["GET"]
)
@require_auth
def get_user_recommendations(session_id, user_id):
    """
    GET /api/sessions/<id>/recommendations/<user_id>
    Returns recommendations for a specific user.
    """
    try:
        session_path = get_session_path(session_id)
    except FileNotFoundError:
        return jsonify({"error": "Session not found"}), 404

    csv_path = os.path.join(session_path, "results", "recommendations.csv")
    if not os.path.isfile(csv_path):
        return jsonify({"error": "No recommendations. Run /mine first."}), 404

    df = pd.read_csv(csv_path, dtype=str)
    df = df[df["USR_ID"] == user_id]

    if df.empty:
        return jsonify({
            "session_id": session_id,
            "user_id": user_id,
            "count": 0,
            "recommendations": [],
        })

    records = df.to_dict(orient="records")
    return jsonify({
        "session_id": session_id,
        "user_id": user_id,
        "count": len(records),
        "recommendations": records,
    })